############################# Filebeat ######################################
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      paths:
        - /usr/share/filebeat/sourcelog/a.log
      input_type: log
      multiline:
        pattern: ^([0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{2}-[aA-zZ]{3}-[0-9]{4})
        negate: true
        match: after
      fields:
        type: tomcat-catalina
      fields_under_root: true
    -
      paths:
        - /usr/share/filebeat/sourcelog/b.log
      input_type: log
      fields:
        type: tomcat-access
      fields_under_root: true

output:
  logstash:
    hosts: ["logstash:5000"]
